function HomePage() {
  return (
    'Pellentesque sed imperdiet nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu purus sed velit pretium elementum tempor vitae nisi. Duis scelerisque mauris id orci auctor, in placerat erat feugiat. Nam consectetur, orci in ultricies pretium, augue nibh interdum turpis, ut pretium orci massa laoreet ipsum. Nulla facilisi. Sed sed lorem sem. Sed dignissim lacinia ex vitae accumsan. Fusce at egestas dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus at pulvinar nulla. Vestibulum finibus quis turpis sit amet porttitor. Sed laoreet ligula massa, at molestie tellus ornare vel.\n' +
    '\n' +
    'Fusce et nisi id nunc efficitur pharetra id in nisl. Ut imperdiet mauris ac maximus accumsan. Sed sed mi nec augue venenatis porta ut at quam. Suspendisse dictum ex in nisi ornare rhoncus. Suspendisse scelerisque imperdiet semper. Cras suscipit semper tellus, at ornare elit gravida malesuada. Pellentesque accumsan, orci vel fringilla ultricies, metus nisl blandit sapien, at dignissim magna ipsum non quam. Aenean at erat in metus fringilla porta vitae quis enim. In hac habitasse platea dictumst. Sed fermentum, sapien nec varius gravida, ante neque maximus leo, id scelerisque dui nibh eu neque.\n' +
    '\n' +
    'Maecenas vehicula leo in orci laoreet dictum. Praesent et mi ante. Proin non lorem varius, rhoncus nunc vitae, porttitor arcu. Etiam at dignissim diam, eget consequat mi. Vestibulum ullamcorper sapien eros, sed facilisis eros pretium at. Proin eleifend ultrices arcu id aliquam. Proin a tempus ex, nec condimentum nibh. Morbi vitae faucibus risus, aliquet porta neque.\n' +
    '\n' +
    'Etiam sollicitudin orci sed lorem placerat, eget dictum quam viverra. Etiam congue mi finibus vestibulum tincidunt. Cras et sem ullamcorper, lacinia ante at, malesuada dui. Sed a tortor aliquet sem elementum molestie et in lacus. Sed blandit tempus enim vitae fermentum. Nam a blandit dui. Proin interdum id magna quis viverra. Donec felis sapien, euismod dignissim orci dignissim, ullamcorper porttitor massa. Aenean at sodales libero. Suspendisse vulputate eu velit in tristique. Vestibulum vitae odio quis lacus pharetra ultricies. Ut nec consectetur ligula, et vehicula orci. Donec porta aliquam enim, ac placerat purus placerat et. Donec nec purus a felis vulputate fermentum nec a sapien. Mauris gravida dolor sit amet ipsum dignissim, id tincidunt ipsum vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n' +
    '\n' +
    'Praesent a finibus quam. Donec efficitur maximus purus at egestas. Vestibulum vel leo ligula. In diam tellus, efficitur id accumsan in, scelerisque sed neque. Proin dapibus massa in fermentum fringilla. Phasellus cursus semper tortor, eu feugiat lectus mattis at. Nullam dapibus nec urna in porta. Quisque dictum posuere augue, ut gravida velit vestibulum fringilla. Vestibulum placerat volutpat malesuada. Nam gravida fermentum leo, vel aliquet magna interdum nec. In eros mi, pulvinar id eros at, aliquam fermentum justo. Suspendisse porttitor vulputate sapien, at efficitur orci dignissim quis. Praesent congue lectus vitae congue lobortis. Quisque fermentum lobortis eros. Nullam dignissim consequat faucibus.\n' +
    '\n' +
    'Pellentesque elit risus, porttitor et justo at, blandit suscipit nisl. Ut vehicula lacus vitae faucibus consequat. Donec eu consectetur lectus, vitae venenatis dolor. Vivamus sed interdum dui. Aliquam maximus libero id sapien eleifend venenatis. Etiam ac tortor semper, scelerisque tortor et, condimentum mi. In tempus tellus vitae faucibus semper. Nunc interdum venenatis elit id sagittis. Proin sit amet elementum turpis, ac sagittis dui. Donec accumsan facilisis ante ut lobortis.\n' +
    '\n' +
    'Duis quis pulvinar lorem. Vestibulum convallis accumsan ante a venenatis. Phasellus tempor vulputate dui vel interdum. Suspendisse dapibus consequat augue non sagittis. Donec vitae velit tortor. Mauris at faucibus libero. Suspendisse ultricies justo lacinia felis molestie, dapibus sollicitudin mi posuere. Aliquam semper blandit eleifend.\n' +
    '\n' +
    'Aenean consectetur, purus quis scelerisque porta, velit lorem dapibus sem, in pharetra ipsum nisi et ex. Vivamus placerat dapibus nisl ut interdum. Phasellus sagittis ornare iaculis. Suspendisse vel lectus eu nunc consectetur vulputate non ac ex. Sed eu nibh sit amet urna porta consequat. Mauris sed eleifend metus, eu volutpat tortor. Proin faucibus non magna ac consequat. Nunc et quam quis turpis tristique tempor pharetra ac massa. Cras quam tellus, cursus a gravida in, gravida id arcu. Morbi rutrum, quam dapibus placerat mollis, ex tellus pretium dolor, at commodo magna ligula at quam. Cras euismod odio non vulputate pharetra. Phasellus in ultrices mauris, ac semper ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu accumsan nibh, vel viverra urna. Mauris posuere leo vitae rhoncus ultricies.\n' +
    '\n' +
    'Quisque nunc risus, porta eget lorem at, volutpat maximus leo. Curabitur interdum eu neque eget molestie. Morbi at pretium leo. Vivamus posuere non est a tristique. Integer posuere felis euismod dictum imperdiet. Aliquam erat volutpat. Aliquam pretium ac sem quis placerat. Sed ullamcorper facilisis diam, a porta elit ornare in.\n' +
    '\n' +
    'Duis mollis mauris vel eros efficitur pretium. Etiam id enim hendrerit, eleifend eros eu, accumsan odio. Ut ullamcorper quam vitae eros molestie, sed hendrerit risus dapibus. Donec viverra mattis fermentum. Fusce eleifend nibh leo. Nunc non convallis lectus, sed efficitur arcu. Phasellus venenatis scelerisque feugiat. Integer rutrum justo quis lacus dapibus bibendum. Donec mattis, leo sit amet finibus rutrum, magna justo feugiat mi, et aliquet tellus velit ac eros. Pellentesque eu ipsum sit amet lorem egestas consectetur vitae feugiat massa. Vivamus id fermentum lectus, ut porttitor nisl. Proin aliquam enim quis purus blandit facilisis. Proin dictum ante ante, eget vehicula sem aliquet pellentesque.'
  );
}

export default HomePage;
